// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Algoliasearch = require("algoliasearch");

function make(applicationId, apiKey, _) {
  return Algoliasearch(applicationId, apiKey);
}

var Client = /* module */[/* make */make];

function make$1(name, algoliaClient) {
  return algoliaClient.initIndex(name);
}

var Index = /* module */[/* make */make$1];

exports.Client = Client;
exports.Index  = Index;
/* algoliasearch Not a pure module */
